uint32 max_candidates
---
bool success
FrontierCandidate[] candidates
uint16 reason_code
string reason_text
uint32 raw_frontier_count
uint32 candidate_count
uint32 blacklist_count
uint64 map_revision
bool exploration_complete
bool recoverable
