---
bool success
geometry_msgs/PoseStamped goal
uint16 reason_code
string reason_text
float32 score
float32 distance_m
float32 clearance_m
uint32 raw_frontier_count
uint32 candidate_count
uint32 blacklist_count
bool exploration_complete
bool recoverable
